In [1]:
import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, f1_score

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

df = pd.read_excel("../data/final_cleaned_dataset.xlsx")
df.head()

,EatLess_OnWeightGain,EatLess_AtMealtime,RefuseFood_WeightConcern,Monitor_Food,Eat_SlimmingFoods,EatLess_AfterOvereating,EatLess_ToPreventWeightGain,AvoidSnacks_BetweenMealsToWatchWeight,AvoidEveningEating_ToWatchWeight,ConsiderWeight_WhenEating,...,Days_ExcludedFoodControlShapeOrWeight_No days,Days_FollowedRulesControlShapeOrWeight_13-15 days,Days_FollowedRulesControlShapeOrWeight_6-12 days,Days_FollowedRulesControlShapeOrWeight_Every day,Days_FollowedRulesControlShapeOrWeight_No days,Days_FearLosingControlOverEating_13-15 days,Days_FearLosingControlOverEating_6-12 days,Days_FearLosingControlOverEating_Every day,Days_FearLosingControlOverEating_No days,target
0,3,3,3,3,3,3,3,3,3,2,...,False,False,False,True,False,False,False,True,False,Probably yes
1,3,2,2,3,2,4,3,4,3,2,...,False,False,False,True,False,False,True,False,False,Probably yes
2,0,0,0,0,0,0,0,0,0,0,...,True,False,False,False,True,False,False,False,True,"Possibly, but I am not sure"
3,2,2,1,3,2,1,3,1,0,2,...,True,False,False,False,True,False,False,False,False,Probably not
4,0,0,0,3,2,0,0,0,2,2,...,True,False,False,False,True,False,False,False,True,"Possibly, but I am not sure"

In [2]:
def simplify_target_3(label):
    if label == "Probably not":
        return "Low"
    elif label == "Possibly, but I am not sure":
        return "Moderate"
    else:
        return "High"

df["target_3class"] = df["target"].apply(simplify_target_3)
df["target_3class"].value_counts()

target_3class
Moderate    246
High        184
Low         120
Name: count, dtype: int64

In [3]:
def simplify_target_3(label):
    if label == "Probably not":
        return "Low"
    elif label == "Possibly, but I am not sure":
        return "Moderate"
    else:
        return "High"

df["target_3class"] = df["target"].apply(simplify_target_3)
df["target_3class"].value_counts()

target_3class
Moderate    246
High        184
Low         120
Name: count, dtype: int64

In [4]:
X = df.drop(columns=["target", "target_3class"]).astype(int)
y = df["target_3class"]

In [5]:
le = LabelEncoder()
y_encoded = le.fit_transform(y)

print("Classes:", list(le.classes_))

Classes: ['High', 'Low', 'Moderate']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

In [8]:
models = {
    "Logistic Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(max_iter=2000, class_weight="balanced"))
    ]),
    
    "SVM": Pipeline([
        ("scaler", StandardScaler()),
        ("model", SVC(class_weight="balanced"))
    ]),
    
    "Random Forest": RandomForestClassifier(
        n_estimators=200,
        random_state=42,
        class_weight="balanced"
    ),
    
    "XGBoost": XGBClassifier(
        objective="multi:softmax",
        num_class=len(le.classes_),
        n_estimators=200,
        learning_rate=0.1,
        max_depth=5,
        random_state=42,
        eval_metric="mlogloss"
    )
}

In [10]:
results = []

for name, model in models.items():
    print(f"\n===== {name} =====")
    
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, average="macro")
    
    results.append({
        "Model": name,
        "Accuracy": acc,
        "F1_macro": f1
    })
    
    print("Accuracy:", acc)
    print("F1 Macro:", f1)
    print(classification_report(y_test, y_pred, target_names=le.classes_))

===== Logistic Regression =====
Accuracy: 0.44545454545454544
F1 Macro: 0.4197487100712907
              precision    recall  f1-score   support

        High       0.41      0.46      0.44        37
         Low       0.28      0.29      0.29        24
    Moderate       0.57      0.51      0.54        49

    accuracy                           0.45       110
   macro avg       0.42      0.42      0.42       110
weighted avg       0.45      0.45      0.45       110


===== SVM =====
Accuracy: 0.44545454545454544
F1 Macro: 0.4092631743794534
              precision    recall  f1-score   support

        High       0.42      0.59      0.49        37
         Low       0.25      0.21      0.23        24
    Moderate       0.59      0.45      0.51        49

    accuracy                           0.45       110
   macro avg       0.42      0.42      0.41       110
weighted avg       0.46      0.45      0.44       110


===== Random Forest =====
Accuracy: 0.4818181818181818
F1 Macro: 0.38431195423065345
              precision    recall  f1-score   support

        High       0.47      0.57      0.51        37
         Low       0.17      0.04      0.07        24
    Moderate       0.53      0.63      0.57        49

    accuracy                           0.48       110
   macro avg       0.39      0.41      0.38       110
weighted avg       0.43      0.48      0.44       110


===== XGBoost =====
Accuracy: 0.4818181818181818
F1 Macro: 0.4185185185185185
              precision    recall  f1-score   support

        High       0.46      0.43      0.44        37
         Low       0.25      0.17      0.20        24
    Moderate       0.56      0.67      0.61        49

    accuracy                           0.48       110
   macro avg       0.42      0.42      0.42       110
weighted avg       0.46      0.48      0.47       110

In [11]:
results_df_3class = pd.DataFrame(results).sort_values(by="F1_macro", ascending=False)
results_df_3class

                 Model  Accuracy  F1_macro
0  Logistic Regression  0.445455  0.419749
3              XGBoost  0.481818  0.418519
1                  SVM  0.445455  0.409263
2        Random Forest  0.481818  0.384312

In [12]:
def simplify_target_2(label):
    if label == "Probably not":
        return "No Risk"
    else:
        return "Risk"

df["target_2class"] = df["target"].apply(simplify_target_2)
df["target_2class"].value_counts()

target_2class
Risk       430
No Risk    120
Name: count, dtype: int64

In [13]:
y = df["target_2class"]

In [14]:
y = df["target_2class"]

In [15]:
from xgboost import XGBClassifier

temp_model = XGBClassifier()
temp_model.fit(X_train, y_train)

import pandas as pd

importance = pd.Series(temp_model.feature_importances_, index=X.columns)
top_features = importance.sort_values(ascending=False).head(30).index

X = X[top_features]

In [18]:
importance = pd.Series(temp_model.feature_importances_, index=X_train.columns)
top_features = importance.sort_values(ascending=False).head(30).index
top_features

Index(['Days_FearLosingControlOverEating_No days',
       'Education_Level_PhD or higher',
       'Days_UncomfortableToSeeOwnBody_Every day', 'Age_Range_Under 18',
       'Days_DissatisfiedWithWeight_13-15 days',
       'Employment_Status_Self-employed',
       'Days_FollowedRulesControlShapeOrWeight_13-15 days',
       'Days_WeightAffectedSelfJudgment_No days',
       'Days_ExcludedFoodControlShapeOrWeight_Every day',
       'Employment_Status_Unemployed', 'Age_Range_35-44',
       'Days_UncomfortableToSeeOwnBody_13-15 days',
       'Days_ExcludedFoodControlShapeOrWeight_13-15 days',
       'Days_UncomfortableBecauseOthersSeeingShape_13-15 days',
       'Days_DesireForFlatStomach_13-15 days',
       'Education_Level_Master's degree',
       'Days_FastedControlShapeOrWeight_Every day',
       'Days_DissatisfiedWithShape_No days',
       'Days_TriedLimitFoodControlShapeOrWeight_13-15 days',
       'Realize_AfterEatingOutOfHabit',
       'Days_ShapeAffectedSelfJudgment_No days',
       'Days_FastedControlShapeOrWeight_No days', 'Eat_WhenAnxious',
       'Eat_SpecificFoodsHabitually', 'DesireToBuy _FromSnackBarOrCafe',
       'AvoidSnacks_BetweenMealsToWatchWeight', 'Eat_DeliciousFoodImmediately',
       'DesireToEat_WhenSeeOthersEating', 'Eat_WhenAngry',
       'Eat_WhenSeeDeliciousFood'],
      dtype='object')

In [19]:
X_top = X[top_features]

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    X_top,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

In [21]:
X = df.drop(columns=["target", "target_3class", "target_2class"], errors="ignore").astype(int)
y = df["target_2class"]

In [22]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

In [24]:
from xgboost import XGBClassifier

temp_model = XGBClassifier(
    objective="binary:logistic",
    random_state=42,
    eval_metric="logloss"
)

temp_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [26]:
import pandas as pd

importance = pd.Series(temp_model.feature_importances_, index=X_train.columns)
top_features = importance.sort_values(ascending=False).head(30).index.tolist()

print(top_features)

['Days_UncomfortableBecauseOthersSeeingShape_Every day', 'Days_FollowedRulesControlShapeOrWeight_13-15 days', 'Days_DissatisfiedWithShape_6-12 days', 'EatLess_OnWeightGain', 'Eat_WhenSeeDeliciousFood', 'Days_WeightAffectedSelfJudgment_Every day', 'Days_UncomfortableToSeeOwnBody_Every day', 'Days_TriedLimitFoodControlShapeOrWeight_Every day', 'Days_DissatisfiedWithWeight_Every day', 'DesireToBuy _FromSnackBarOrCafe', 'Days_TriedLimitFoodControlShapeOrWeight_13-15 days', "Education_Level_Master's degree", 'Realize_AfterEatingOutOfHabit', 'EatMore_WhenSeeOthersEating', 'AvoidEveningEating_ToWatchWeight', 'Eat_WhenAnxious', 'Monitor_Food', 'Eat_DeliciousFoodImmediately', 'Eat_WhenExpectingBad', 'Days_DissatisfiedWithShape_Every day', 'Location_TriggersHabitualEating', 'Eat_WhenBoredOrRestless', 'Education_Level_High school or below', 'Days_FastedControlShapeOrWeight_13-15 days', 'DesireToBuy_FromBakery', 'EatLess_AfterOvereating', 'Employment_Status_Student', 'Days_ExcludedFoodControlShapeOrWeight_Every day', 'AvoidSnacks_BetweenMealsToWatchWeight', 'Days_WeightAffectedSelfJudgment_6-12 days']

In [27]:
X_top = X[top_features]

In [28]:
X_train, X_test, y_train, y_test = train_test_split(
    X_top,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

In [29]:
X_train, X_test, y_train, y_test = train_test_split(
    X_top,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

In [30]:
X = df.drop(columns=["target", "target_3class", "target_2class"], errors="ignore").astype(int)
y = df["target_2class"]

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

In [32]:
from xgboost import XGBClassifier
import pandas as pd

temp_model = XGBClassifier(
    objective="binary:logistic",
    random_state=42,
    eval_metric="logloss"
)

temp_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [33]:
importance = pd.Series(temp_model.feature_importances_, index=X_train.columns)
top_features = importance.sort_values(ascending=False).head(30).index.tolist()

print(top_features)

['Days_UncomfortableBecauseOthersSeeingShape_Every day', 'Days_FollowedRulesControlShapeOrWeight_13-15 days', 'Days_DissatisfiedWithShape_6-12 days', 'EatLess_OnWeightGain', 'Eat_WhenSeeDeliciousFood', 'Days_WeightAffectedSelfJudgment_Every day', 'Days_UncomfortableToSeeOwnBody_Every day', 'Days_TriedLimitFoodControlShapeOrWeight_Every day', 'Days_DissatisfiedWithWeight_Every day', 'DesireToBuy _FromSnackBarOrCafe', 'Days_TriedLimitFoodControlShapeOrWeight_13-15 days', "Education_Level_Master's degree", 'Realize_AfterEatingOutOfHabit', 'EatMore_WhenSeeOthersEating', 'AvoidEveningEating_ToWatchWeight', 'Eat_WhenAnxious', 'Monitor_Food', 'Eat_DeliciousFoodImmediately', 'Eat_WhenExpectingBad', 'Days_DissatisfiedWithShape_Every day', 'Location_TriggersHabitualEating', 'Eat_WhenBoredOrRestless', 'Education_Level_High school or below', 'Days_FastedControlShapeOrWeight_13-15 days', 'DesireToBuy_FromBakery', 'EatLess_AfterOvereating', 'Employment_Status_Student', 'Days_ExcludedFoodControlShapeOrWeight_Every day', 'AvoidSnacks_BetweenMealsToWatchWeight', 'Days_WeightAffectedSelfJudgment_6-12 days']

In [34]:
X_top = X[top_features]
print(X_top.shape)

(550, 30)

In [35]:
X_train, X_test, y_train, y_test = train_test_split(
    X_top,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

In [36]:
from sklearn.metrics import accuracy_score, classification_report, f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

models_2class = {
    "Logistic Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(max_iter=2000, class_weight="balanced"))
    ]),
    
    "SVM": Pipeline([
        ("scaler", StandardScaler()),
        ("model", SVC(class_weight="balanced"))
    ]),
    
    "Random Forest": RandomForestClassifier(
        n_estimators=200,
        random_state=42,
        class_weight="balanced"
    ),
    
    "XGBoost": XGBClassifier(
        objective="binary:logistic",
        n_estimators=200,
        learning_rate=0.1,
        max_depth=5,
        random_state=42,
        eval_metric="logloss"
    )
}

In [37]:
results = []

for name, model in models_2class.items():
    print(f"\n===== {name} =====")
    
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, average="macro")
    
    results.append({
        "Model": name,
        "Accuracy": acc,
        "F1_macro": f1
    })
    
    print("Accuracy:", acc)
    print("F1 Macro:", f1)
    print(classification_report(y_test, y_pred, target_names=le.classes_))

===== Logistic Regression =====
Accuracy: 0.6363636363636364
F1 Macro: 0.5592948717948718
              precision    recall  f1-score   support

     No Risk       0.30      0.50      0.38        24
        Risk       0.83      0.67      0.74        86

    accuracy                           0.64       110
   macro avg       0.56      0.59      0.56       110
weighted avg       0.71      0.64      0.66       110


===== SVM =====
Accuracy: 0.6818181818181818
F1 Macro: 0.5946941783345616
              precision    recall  f1-score   support

     No Risk       0.34      0.50      0.41        24
        Risk       0.84      0.73      0.78        86

    accuracy                           0.68       110
   macro avg       0.59      0.62      0.59       110
weighted avg       0.73      0.68      0.70       110


===== Random Forest =====
Accuracy: 0.8
F1 Macro: 0.5202220459952418
              precision    recall  f1-score   support

     No Risk       1.00      0.08      0.15        24
        Risk       0.80      1.00      0.89        86

    accuracy                           0.80       110
   macro avg       0.90      0.54      0.52       110
weighted avg       0.84      0.80      0.73       110


===== XGBoost =====
Accuracy: 0.7636363636363637
F1 Macro: 0.5864661654135338
              precision    recall  f1-score   support

     No Risk       0.43      0.25      0.32        24
        Risk       0.81      0.91      0.86        86

    accuracy                           0.76       110
   macro avg       0.62      0.58      0.59       110
weighted avg       0.73      0.76      0.74       110

In [38]:
results_df_2class = pd.DataFrame(results).sort_values(by="F1_macro", ascending=False)
results_df_2class

                 Model  Accuracy  F1_macro
1                  SVM  0.681818  0.594694
3              XGBoost  0.763636  0.586466
0  Logistic Regression  0.636364  0.559295
2        Random Forest  0.800000  0.520222